/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetobancodados;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jplim
 */
public class TelaInicialAluno extends javax.swing.JFrame {

    String matricula;
    Connection con;
    Boolean Admin;
    public TelaInicialAluno() {
        initComponents();
    }
    
    public TelaInicialAluno(String Matricula) {
        initComponents();
        matricula = Matricula;
        try {
            con =DriverManager.getConnection("jdbc:mysql://localhost/avaliacao_turma","root","");
            PreparedStatement ps =con.prepareStatement("select * from Aluno where Aluno.matricula= ?");
            ps.setString(1, matricula);
            ResultSet rs = ps.executeQuery();
            if (rs.next()==true){
                Admin=rs.getBoolean(6);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TelaInicialAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPerfil = new javax.swing.JMenu();
        jMenuMeusDados = new javax.swing.JMenuItem();
        jMenuMinAval = new javax.swing.JMenuItem();
        jMenuMinDen = new javax.swing.JMenuItem();
        jMenuTurma = new javax.swing.JMenu();
        jMenuAvaliaTurma = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuAvaliaDenun = new javax.swing.JMenuItem();
        criarAdmin = new javax.swing.JMenuItem();
        jMenuOpcoes = new javax.swing.JMenu();
        opcoesDeslogar = new javax.swing.JMenuItem();
        opcoesSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuPerfil.setText("Meu Perfil");

        jMenuMeusDados.setText("Meus Dados");
        jMenuMeusDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMeusDadosActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuMeusDados);

        jMenuMinAval.setText("Minhas Avaliacoes");
        jMenuMinAval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMinAvalActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuMinAval);

        jMenuMinDen.setText("Minhas Denuncias");
        jMenuMinDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMinDenActionPerformed(evt);
            }
        });
        jMenuPerfil.add(jMenuMinDen);

        jMenuBar1.add(jMenuPerfil);

        jMenuTurma.setText("Turma");

        jMenuAvaliaTurma.setText("Avaliar Turmas");
        jMenuAvaliaTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAvaliaTurmaActionPerformed(evt);
            }
        });
        jMenuTurma.add(jMenuAvaliaTurma);

        jMenuBar1.add(jMenuTurma);

        jMenuAdmin.setText("Admin");

        jMenuAvaliaDenun.setText("Julgar Denuncias");
        jMenuAvaliaDenun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAvaliaDenunActionPerformed(evt);
            }
        });
        jMenuAdmin.add(jMenuAvaliaDenun);

        criarAdmin.setText("Criar Admins");
        criarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarAdminActionPerformed(evt);
            }
        });
        jMenuAdmin.add(criarAdmin);

        jMenuBar1.add(jMenuAdmin);

        jMenuOpcoes.setText("Opcoes");

        opcoesDeslogar.setText("Deslogar");
        opcoesDeslogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoesDeslogarActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(opcoesDeslogar);

        opcoesSair.setText("Sair");
        opcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcoesSairActionPerformed(evt);
            }
        });
        jMenuOpcoes.add(opcoesSair);

        jMenuBar1.add(jMenuOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMeusDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMeusDadosActionPerformed
        new Dados_do_Aluno(this.matricula,this).setVisible(true);
    }//GEN-LAST:event_jMenuMeusDadosActionPerformed

    private void jMenuAvaliaTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAvaliaTurmaActionPerformed
        new SelecionarTurma(this.matricula).setVisible(true);
    }//GEN-LAST:event_jMenuAvaliaTurmaActionPerformed

    private void jMenuAvaliaDenunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAvaliaDenunActionPerformed
        if(Admin==true){
            new SelecionarDenuncia(matricula).setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Você não é administrador");
        }
    }//GEN-LAST:event_jMenuAvaliaDenunActionPerformed

    private void jMenuMinAvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMinAvalActionPerformed
        new MinhasAvaliacoes(matricula).setVisible(true);
    }//GEN-LAST:event_jMenuMinAvalActionPerformed

    private void jMenuMinDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMinDenActionPerformed
        new MinhasDenuncias(matricula).setVisible(true);
    }//GEN-LAST:event_jMenuMinDenActionPerformed

    private void opcoesDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoesDeslogarActionPerformed
        new TelaInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_opcoesDeslogarActionPerformed

    private void opcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcoesSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_opcoesSairActionPerformed

    private void criarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarAdminActionPerformed
        if(Admin==true){
            new CriarAdmin().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"Você não é administrador");
        }
    }//GEN-LAST:event_criarAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem criarAdmin;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuItem jMenuAvaliaDenun;
    private javax.swing.JMenuItem jMenuAvaliaTurma;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuMeusDados;
    private javax.swing.JMenuItem jMenuMinAval;
    private javax.swing.JMenuItem jMenuMinDen;
    private javax.swing.JMenu jMenuOpcoes;
    private javax.swing.JMenu jMenuPerfil;
    private javax.swing.JMenu jMenuTurma;
    private javax.swing.JMenuItem opcoesDeslogar;
    private javax.swing.JMenuItem opcoesSair;
    // End of variables declaration//GEN-END:variables
}
